// <auto-generated />
using System;
using DevsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevsApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221022030234_GuruDevs")]
    partial class GuruDevs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevsApi.Models.DevsHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammingLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DevsHeroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "AbuBakarr Kamara",
                            CreatedDate = new DateTime(2022, 10, 21, 20, 2, 33, 967, DateTimeKind.Local).AddTicks(4592),
                            Name = "Emmanuel Foday Kamara",
                            ProgrammingLanguage = "Python",
                            Project = "AI EXPLORATION",
                            location = "Locust Junction, Quarry."
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "AbuBakarr Kamara",
                            CreatedDate = new DateTime(2022, 10, 21, 20, 2, 33, 967, DateTimeKind.Local).AddTicks(4642),
                            Name = "AbuBakarr Kamara",
                            ProgrammingLanguage = ".net",
                            Project = "AI EXPLORATION",
                            location = " Junction, Quarry."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
